/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MultiplicationService_H
#define MultiplicationService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "multiple_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class MultiplicationServiceIf {
 public:
  virtual ~MultiplicationServiceIf() {}
  virtual int multiply(const int n1, const int n2) = 0;
};

class MultiplicationServiceIfFactory {
 public:
  typedef MultiplicationServiceIf Handler;

  virtual ~MultiplicationServiceIfFactory() {}

  virtual MultiplicationServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MultiplicationServiceIf* /* handler */) = 0;
};

class MultiplicationServiceIfSingletonFactory : virtual public MultiplicationServiceIfFactory {
 public:
  MultiplicationServiceIfSingletonFactory(const boost::shared_ptr<MultiplicationServiceIf>& iface) : iface_(iface) {}
  virtual ~MultiplicationServiceIfSingletonFactory() {}

  virtual MultiplicationServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MultiplicationServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<MultiplicationServiceIf> iface_;
};

class MultiplicationServiceNull : virtual public MultiplicationServiceIf {
 public:
  virtual ~MultiplicationServiceNull() {}
  int multiply(const int /* n1 */, const int /* n2 */) {
    int _return = 0;
    return _return;
  }
};

typedef struct _MultiplicationService_multiply_args__isset {
  _MultiplicationService_multiply_args__isset() : n1(false), n2(false) {}
  bool n1 :1;
  bool n2 :1;
} _MultiplicationService_multiply_args__isset;

class MultiplicationService_multiply_args {
 public:

  MultiplicationService_multiply_args(const MultiplicationService_multiply_args&);
  MultiplicationService_multiply_args& operator=(const MultiplicationService_multiply_args&);
  MultiplicationService_multiply_args() : n1(0), n2(0) {
  }

  virtual ~MultiplicationService_multiply_args() throw();
  int n1;
  int n2;

  _MultiplicationService_multiply_args__isset __isset;

  void __set_n1(const int val);

  void __set_n2(const int val);

  bool operator == (const MultiplicationService_multiply_args & rhs) const
  {
    if (!(n1 == rhs.n1))
      return false;
    if (!(n2 == rhs.n2))
      return false;
    return true;
  }
  bool operator != (const MultiplicationService_multiply_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MultiplicationService_multiply_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MultiplicationService_multiply_pargs {
 public:


  virtual ~MultiplicationService_multiply_pargs() throw();
  const int* n1;
  const int* n2;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MultiplicationService_multiply_result__isset {
  _MultiplicationService_multiply_result__isset() : success(false) {}
  bool success :1;
} _MultiplicationService_multiply_result__isset;

class MultiplicationService_multiply_result {
 public:

  MultiplicationService_multiply_result(const MultiplicationService_multiply_result&);
  MultiplicationService_multiply_result& operator=(const MultiplicationService_multiply_result&);
  MultiplicationService_multiply_result() : success(0) {
  }

  virtual ~MultiplicationService_multiply_result() throw();
  int success;

  _MultiplicationService_multiply_result__isset __isset;

  void __set_success(const int val);

  bool operator == (const MultiplicationService_multiply_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MultiplicationService_multiply_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MultiplicationService_multiply_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MultiplicationService_multiply_presult__isset {
  _MultiplicationService_multiply_presult__isset() : success(false) {}
  bool success :1;
} _MultiplicationService_multiply_presult__isset;

class MultiplicationService_multiply_presult {
 public:


  virtual ~MultiplicationService_multiply_presult() throw();
  int* success;

  _MultiplicationService_multiply_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MultiplicationServiceClient : virtual public MultiplicationServiceIf {
 public:
  MultiplicationServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MultiplicationServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int multiply(const int n1, const int n2);
  void send_multiply(const int n1, const int n2);
  int recv_multiply();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MultiplicationServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MultiplicationServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MultiplicationServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_multiply(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MultiplicationServiceProcessor(boost::shared_ptr<MultiplicationServiceIf> iface) :
    iface_(iface) {
    processMap_["multiply"] = &MultiplicationServiceProcessor::process_multiply;
  }

  virtual ~MultiplicationServiceProcessor() {}
};

class MultiplicationServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MultiplicationServiceProcessorFactory(const ::boost::shared_ptr< MultiplicationServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MultiplicationServiceIfFactory > handlerFactory_;
};

class MultiplicationServiceMultiface : virtual public MultiplicationServiceIf {
 public:
  MultiplicationServiceMultiface(std::vector<boost::shared_ptr<MultiplicationServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MultiplicationServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MultiplicationServiceIf> > ifaces_;
  MultiplicationServiceMultiface() {}
  void add(boost::shared_ptr<MultiplicationServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int multiply(const int n1, const int n2) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->multiply(n1, n2);
    }
    return ifaces_[i]->multiply(n1, n2);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class MultiplicationServiceConcurrentClient : virtual public MultiplicationServiceIf {
 public:
  MultiplicationServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  MultiplicationServiceConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int multiply(const int n1, const int n2);
  int32_t send_multiply(const int n1, const int n2);
  int recv_multiply(const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
