/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "multiple_constants.h"



const multipleConstants g_multiple_constants;

multipleConstants::multipleConstants() {
}



