/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef multiple_CONSTANTS_H
#define multiple_CONSTANTS_H

#include "multiple_types.h"



class multipleConstants {
 public:
  multipleConstants();

};

extern const multipleConstants g_multiple_constants;



#endif
